version: "3"

services:
  build-rs:
    build:
      dockerfile: ./dockerfiles/build-rs/Dockerfile
      context: ..

  tsplay:
    build:
      dockerfile: ./dockerfiles/tsplay/Dockerfile
      context: ..
    volumes:
      - /tmp/va-dumps/:/mnt/dumps/
